/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    screens: {
      sm: '375px',
      md: '768px',
      lg: '1024px',
      xl: '1200px',
      '2xl': '1440px',
    },
    colors: {
      primary: '#8B000F',
      wine: '#6E000C',
      'soft-pink': '#E6B6D3',
      'light-pink': '#F3D4E6',
      'off-white': '#F9F6F8',
      white: '#FFFFFF',
      transparent: 'transparent',
      current: 'currentColor',
    },
    fontFamily: {
      heading: ['var(--font-jacquard)'],
      body: ['var(--font-poppins)'],
    },
    fontSize: {
      /* Desktop */
      'hero-dt': ['100px', { lineHeight: '1.0', letterSpacing: '-0.02em' }],
      'podcast-dt': ['80px', { lineHeight: '1.0', letterSpacing: '-0.01em' }],
      'merch-dt': ['150px', { lineHeight: '0.9', letterSpacing: '-0.03em' }],
      'stanley-dt': ['100px', { lineHeight: '1.0', letterSpacing: '-0.02em' }],
      'waitlist-dt': ['100px', { lineHeight: '1.0', letterSpacing: '-0.02em' }],
      'btn-dt': ['35px', { lineHeight: '1.2' }],
      'body-dt': ['25px', { lineHeight: '1.6' }],
      'footer-dt': ['25px', { lineHeight: '1.6' }],
      /* Mobile */
      'hero-mb': ['48px', { lineHeight: '1.05', letterSpacing: '-0.02em' }],
      'podcast-mb': ['38px', { lineHeight: '1.05', letterSpacing: '-0.01em' }],
      'merch-mb': ['64px', { lineHeight: '0.9', letterSpacing: '-0.02em' }],
      'stanley-mb': ['48px', { lineHeight: '1.0', letterSpacing: '-0.02em' }],
      'waitlist-mb': ['48px', { lineHeight: '1.0', letterSpacing: '-0.02em' }],
      'btn-mb': ['18px', { lineHeight: '1.2' }],
      'body-mb': ['16px', { lineHeight: '1.7' }],
      'footer-mb': ['16px', { lineHeight: '1.6' }],
    },
    spacing: {
      0: '0px',
      1: '8px',
      2: '16px',
      3: '24px',
      4: '32px',
      5: '40px',
      6: '48px',
      7: '56px',
      8: '64px',
      9: '72px',
      10: '80px',
      11: '88px',
      12: '96px',
      13: '104px',
      14: '112px',
      15: '120px',
      16: '128px',
      18: '144px',
      20: '160px',
      24: '192px',
      28: '224px',
      32: '256px',
      36: '288px',
      40: '320px',
      48: '384px',
      56: '448px',
      64: '512px',
    },
    maxWidth: {
      container: '1200px',
      full: '100%',
      none: 'none',
    },
    borderRadius: {
      none: '0',
      full: '9999px',
    },
    extend: {
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        },
      },
      animation: {
        marquee: 'marquee 28s linear infinite',
      },
    },
  },
  plugins: [],
}
